/** RFC 4180-style CSV with UTF-8 BOM for Excel and CRLF record separators. */
export type CsvValue = string | number | boolean | null | undefined;
export type CsvReport = {
  headings: readonly string[];
  rows: readonly (readonly CsvValue[])[];
};

function cell(value: CsvValue): string {
  if (typeof value === "number" && !Number.isFinite(value))
    throw new Error("Report contains an invalid number.");
  let text = value == null ? "" : String(value);
  // Quote escaping alone does not stop spreadsheet formulas. Include leading
  // whitespace/control characters and full-width formula prefixes. Numbers
  // generated by calculations remain numeric, including negative values.
  if (
    typeof value === "string" &&
    (/^[\s\u0000-\u001f\u007f-\u009f]*[=+@\-＝＋＠－]/u.test(text) ||
      /^[\t\r\n]/.test(text))
  )
    text = "'" + text;
  return '"' + text.replace(/"/g, '""') + '"';
}
export function serializeCsv(report: CsvReport): string {
  if (!report.headings.length)
    throw new Error("Report columns are unavailable.");
  return (
    "\uFEFF" +
    [report.headings, ...report.rows]
      .map((row) => {
        if (row.length !== report.headings.length)
          throw new Error("Report row is incomplete.");
        return row.map(cell).join(",");
      })
      .join("\r\n") +
    "\r\n"
  );
}
export function csvFilename(name: string, now = new Date()): string {
  const slug = name
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 100)
    .replace(/-$/, "");
  return `${slug || "report"}-${now.toISOString().slice(0, 10)}.csv`;
}
/** ISO 8601 UTC, never the browser's locale. Missing timestamps stay empty. */
export function csvTimestamp(value?: string | null): string {
  if (!value) return "";
  const date = new Date(value);
  if (!Number.isFinite(date.getTime()))
    throw new Error("Report contains an invalid timestamp.");
  return date.toISOString();
}
export function downloadCsv(report: CsvReport, name: string): void {
  const text = serializeCsv(report); // Finish all validation before creating a download.
  const url = URL.createObjectURL(
    new Blob([text], { type: "text/csv;charset=utf-8" }),
  );
  const link = document.createElement("a");
  try {
    link.href = url;
    link.download = csvFilename(name);
    link.hidden = true;
    document.body.appendChild(link);
    link.click();
  } finally {
    link.remove();
    // Allow browsers to consume the Blob before releasing it.
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  }
}
