import type { Content } from "./types";
const base = {
  body: "",
  folder: "",
  status: "published" as const,
  version: 1,
  updatedAt: "2026-09-18T12:00:00.000Z",
  duration: 8,
  groups: [],
  lessons: [],
  questions: [],
};
export const seedContent: Content[] = [
  ...[
    [
      "start",
      "Welcome to your fieldbook",
      "Start here",
      "Getting started",
      "Your starting point for knowledge, updates, and learning.",
    ],
    [
      "platform",
      "Platform overview",
      "Product knowledge",
      "Platform essentials",
      "A shared understanding of the platform and the problems it solves.",
    ],
    [
      "value",
      "The value conversation",
      "Sales motions",
      "Discovery",
      "Connect customer priorities to a clear business outcome.",
    ],
    [
      "discovery",
      "Discovery checklist",
      "Sales motions",
      "Discovery",
      "A practical guide for your next customer conversation.",
    ],
    [
      "handoff",
      "Making a great handoff",
      "Processes",
      "Working together",
      "Keep context moving from one team to the next.",
    ],
  ].map(([id, title, category, folder, summary]) => ({
    ...base,
    id,
    kind: "doc" as const,
    title,
    category,
    folder,
    summary,
    body: `## The essentials\n\n${summary} This is sample content for your team to make its own.\n\n## What you need to know\n\nA useful field guide makes the next step clear. Keep the context concise, explain why it matters, and give people a practical starting point.\n\n- Start with the customer’s goal.\n- Build a shared understanding of the problem.\n- Agree on a clear next step.\n\n> Replace this example with your approved field knowledge.\n\n## Put it into practice\n\nUse this guide before your next conversation. Capture the details that matter and share them with your team.`,
  })),
  ...[
    [
      "brief-1",
      "Your weekly field notes",
      "Weekly newsletter",
      "A little less noise. The updates worth knowing this week.",
    ],
    [
      "brief-2",
      "A new chapter for the platform",
      "Launch brief",
      "What changed, why it matters, and how to talk about it.",
    ],
    [
      "brief-3",
      "Small improvements, better conversations",
      "Field update",
      "Fresh resources to help you prepare for your next meeting.",
    ],
  ].map(([id, title, category, summary], i) => ({
    ...base,
    id,
    kind: "brief" as const,
    title,
    category,
    summary,
    updatedAt: `2026-09-${18 - i * 3}T12:00:00.000Z`,
    body: `## In this edition\n\n${summary}\n\n### What’s new\n\nThis sample brief brings the most relevant updates together in one place. Link to evergreen documentation when readers need more depth.\n\n### What it means for the field\n\nFocus on the customer problem, the practical change, and the action your team should take.\n\n### Your next step\n\nExplore the knowledge library and complete the related course in your For you collection.`,
  })),
  ...[
    [
      "course-1",
      "Start with the customer",
      "Sales foundations",
      "Build a strong foundation for every customer conversation.",
      12,
      ["sales"],
    ],
    [
      "course-2",
      "Know the platform",
      "Product essentials",
      "The core concepts, explained in plain language.",
      9,
      ["sales", "solutions"],
    ],
    [
      "course-3",
      "From discovery to next steps",
      "Sales foundations",
      "Turn a good conversation into a shared plan.",
      15,
      ["sales"],
    ],
    [
      "course-4",
      "Bring the story to life",
      "Product essentials",
      "Connect a product capability to a meaningful outcome.",
      10,
      ["solutions"],
    ],
    [
      "course-5",
      "Better together",
      "Ways of working",
      "Build the habits that help your team move together.",
      6,
      [],
    ],
    [
      "course-6",
      "A clear customer handoff",
      "Ways of working",
      "Share the right context at the right moment.",
      8,
      [],
    ],
  ].map(([id, title, category, summary, duration, groups]) => ({
    ...base,
    id: String(id),
    kind: "course" as const,
    title: String(title),
    category: String(category),
    summary: String(summary),
    duration: Number(duration),
    groups: groups as string[],
    lessons: [
      {
        id: `${id}-1`,
        title: "The big idea",
        body: `## ${title}\n\n${summary}\n\nThis short example lesson shows how text-based learning works. Replace it with the context, examples, and practical advice your field team needs.\n\n### Three things to remember\n\n1. Understand the customer’s goal.\n2. Make the value clear.\n3. Agree on a useful next step.`,
      },
      {
        id: `${id}-2`,
        title: "Put it into practice",
        body: "## Make it your own\n\nThink about an upcoming customer conversation. What would you do differently based on this lesson?\n\nWrite down one question you want to ask and one outcome you want to reach. Then complete the knowledge check.",
      },
    ],
    questions: [
      {
        id: `${id}-q1`,
        prompt: "What should you understand first?",
        options: [
          "The customer’s goal",
          "Every available feature",
          "The meeting length",
        ],
        answer: 0,
      },
      {
        id: `${id}-q2`,
        prompt: "How should a useful conversation end?",
        options: [
          "With more slides",
          "With an agreed next step",
          "Without a follow-up",
        ],
        answer: 1,
      },
    ],
  })),
];
